@startuml
skinparam defaultTextAlignment left
caption Behavior of thing POT
[*] --> POT
state POT{
state READY_1{
	READY_1 : clock?ms25_tic / \naction do\n	potValue!read_value(getValue(PIN))\nend\n
}
[*] --> READY_1
}
@enduml
