@startuml
caption Things used in configuration Base
class Base <<(T,#5BBF09)PIM>> {
..▼ Port timer ▼..
▶ timer_timeout
◀ timer_start
◀ timer_cancel
..▼ Port ledRed ▼..
◀ led_ON
◀ led_OFF
..▼ Port pot ▼..
▶ read_value
}
class TimerMsgs <<(F,#BC74ED)Fragment>> {
..Messages..
-timer_start(...)
-timer_cancel(...)
-timer_timeout(...)
-ms25_tic()
-ms100_tic()
-ms500_tic()
}
class LEDMsgs <<(T,#5BBF09)PIM>> {
..Messages..
-led_ON()
-led_OFF()
}
class POTmsgs <<(F,#BC74ED)Fragment>> {
..Messages..
-read_value(...)
}
class POT <<(T,#F94918)PSM>> {
..▼ Port clock ▼..
▶ ms25_tic
..▲ Port potValue ▲..
◀ read_value
}
class LED <<(T,#F94918)PSM>> {
..▲ Port ctrl ▲..
▶ led_ON
▶ led_OFF
}
TimerMsgs <|-- Base
LEDMsgs <|-- Base
POTmsgs <|-- Base
POTmsgs <|-- POT
TimerMsgs <|-- POT
LEDMsgs <|-- LED
@enduml